# Generated by Django 5.2.10 on 2026-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="employee_id",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
